version: "3.10"
services:
  app:
    container_name: employee-tree-django
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    hostname: employee-tree
    ports:
      - "8000:8000"
    volumes:
      - ./:/code
#    networks:
#      backend:
#        ipv4_address: 172.16.238.2
    depends_on:
      - postgres_docker

#  postgres_docker:
#    container_name: postgres_docker
#    image: postgres:14.1-alpine
#    volumes:
#      - ./db:/var/lib/postgresql/data
#    build:
#      context: ./
#      dockerfile: Dockerfile.db
#    restart: always
#    env_file:
#      - ./treeEmployeeStructure/treeEmployeeStructure/.env
#    hostname: postgres-db
#    ports:
#      - "5432:5432"
#    networks:
#      backend:
#        ipv4_address: 172.16.238.3

#  postgres_docker:
#      image: postgres:14-alpine
#      env_file:
#        - ./treeEmployeeStructure/treeEmployeeStructure/.env
##      environment:
##        POSTGRES_DB: "habrdb"
##        POSTGRES_USER: "habrpguser"
##        POSTGRES_PASSWORD: "pgpwd4habr"
##        PGDATA: "/var/lib/postgresql/data/pgdata"
#      volumes:
#        - ../2. Init Database:/docker-entrypoint-initdb.d
#        - .:/var/lib/postgresql/data
#      ports:
#        - "5432:5432"
  postgres_docker:
      image: postgres:14-alpine
      environment:
        POSTGRES_DB: "postgres"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres_db"
        POSTGRES_PORT: 5432
      restart: always

networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
