version: '3.8'

volumes:
  postgres_data:
  static:
  admin-interface:

services:
  postgres_docker:
    image: postgres:14-alpine
    restart:
      always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgres_initialization/db_dump.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./treeEmployeeStructure/treeEmployeeStructure/.env

  django:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres_docker
    restart:
      always
    env_file:
      - ./treeEmployeeStructure/treeEmployeeStructure/.env
    volumes:
      - static:/code/treeEmployeeStructure/static
      - admin-interface:/code/treeEmployeeStructure/admin-interface
    entrypoint:
      /code/entrypoint.sh
    expose:
      - 8000

  nginx:
    image: nginx:1.19.0-alpine
    ports:
      - "80:80"
    volumes:
      - static:/code/treeEmployeeStructure/static
      - admin-interface:/code/treeEmployeeStructure/admin-interface
      - ./nginx_conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django
    restart:
      always
